[package]
name = "server"
version = "0.1.0"
authors = ["Alberto Leal <mailforalberto@gmail.com>"]

[dependencies]
hyper = { git = "https://github.com/hyperium/hyper", rev = "b5a888b0dfb4d6657e00a662257b571d56bda2e7" }
